### PR TITLE
Merge steamcache and generic (rewrite)

### PR DESCRIPTION
**Pull request by kixelated**
I've changed so many things that I don't think you'll want to accept this pull request, but maybe the changes can be a source of inspiration.

Steamcache normally uses `try_files` and `proxy_store` to save files to disk using steam's URI format. Generic, on the other hand, uses `proxy_cache` and stores files based on the md5 of `proxy_cache_key` (in our case, the URI). I'm using `proxy_cache` for both now so all files are stored in the same directory and have an enforced max_size. There are more pros and cons but I like the consistency.

The nginx configuration has been inspired primarily by multiplay/lancache. Many of their configuration changes are required to fix clients, such as the League client which does not work at all using the current generic settings. I tried to keep things simple unlike their repository (it's broken up into a million files for no reason).

There are a lot of little changes, such as logging to stdout/stderr and treating `/data` as a single volume. I removed watchlog because it didn't seem useful enough to port. Let me know if you have any questions or comments.

I've been running this code for our 20 gaming PCs here at Twitch. We've already run into a few issues and fixed them, but everything seems to be working fine.

### CODE REVIEW

**Comment by zatricky** [comment]
A rebase with more meaningful commit messages would probably get more meaningful traffic looking at the work you've contributed.

Re lancache: "it's broken up into a million files for no reason"
They do this because it was/is simpler to maintain. Minor changes for multiplay/lancache require a change only to one or two lines in one file rather than duplicate changes to multiple files (or sections of the same file). Maybe things have changed - but it definitely made sense when they first deployed it.

**Comment by astrolox** [comment]
To be honest it's very hard for us to find time to do big reviews.

**Comment by JasonRivers** [comment]
I have had a quick review but nothing too much.
Some notes here though:

This would all be much easier for us to deal with the PR if it was broken down into sections. Creating many small PR's is much better than 1 PR with many changes, we can't merge until we've fully tested everything. (don't send PR's from your master if that has all of your changes, create branches for the change you want to do and send a PR from that branch).

Files have been removed that are used, E.G. watchlog.sh - This is used by a few people, removing these files means those people don't have the functionality they have been using, Sure this script might not be efficient, but it does work and people are using it.

This has changes that bring it closer to a generic cache, but this is the steamcache, we have a generic cache over at https://github.com/steamcache/generic This PR would be much more suited in there, If we run a single image it will be the generic, eventually this image MAY go away if the generic image proves to be better for everyone (or it will stay as only a steamcache).

Because of these reasons, I can't merge this PR, As we stated in your PR for the DNS, we can't remove functionality that people are using. For a generic cache, Please use the steamcache/generic image.

**Comment by kixelated** [comment]
Hey guys, thanks for the comments. I originally wasn't planning on trying to merge my changes into upstream steamcache but after making somewhat meaningful changes to steamcache-dns and steamcache-sni, I figured I'd just throw up the code review and collect feedback. That's why the commits are kind of arbitrary and there's FAR too many changes bundled into one review. I can put an effort in next time if there's merit in my changes.

@JasonRivers I actually started with generic as the base, but rebased primarily because I don't think there should be separate `steamcache` and `generic` projects. This is obviously a much larger discussion and I realize throwing up this code review was not the best way to raise the topic. The technical difference between the two projects is that `generic` hashes the filename, otherwise we're maintaining two nearly identical (one with fewer features) but incompatible repositories. We can start by improving `generic` until it's good enough (and actually works) but I strongly feel `steamcache` and `generic` should be merged.

And I removed watchlog.sh because it wasn't compatible with the docker way of logging (sent to stdout instead of /data/logs). The script would have to be modified so it doesn't tail a directory and it was just easier to hold off on that.

@zatricky I was also using lancache before switching to this steamcache because of the docker support. Lancache is great because they've addressed the edge cases instead of trying a one-size-fits-all like `generic` which does not work. Every configuration has a purpose otherwise some service stops working. That being said, [lancache](https://github.com/multiplay/lancache/tree/master/lancache) is broken up into 20 very small files which makes it difficult to follow. My fork just shrinks that down to 6 files for the same behavior.

**Pull request closed without merging**
