### PR TITLE
Fix typo in Usage example

### PR DESCRIPTION
**Pull request by JasonDyalog**
Probably my bad - I think I wrote the example!

### CODE REVIEW

**Comment by JasonRivers** [comment]
Bah The pull request came in from my work account, but the commits didn't...

I noticed the latest pull didn't actual load the steamcache server, when I got it to load it just error'd in steam because the resolver wasn't set.

Also - your dockerhub is failing because the relocation of the dockerfile.

**Comment by mintopia** [comment]
We need to move the project over to the steamcache github organisation, I'll see about sorting that tomorrow night, then we can pull this in, split out the two containers and also get dockerhub working again.

I've already updated epic to use a wildcard for *.cs.steampowered.com for that reason.

**Comment by JasonRivers** [comment]
Yep, I figured that's what you would do. If you want to give us access to create repos on it, then I'm happy to upload the DNS server for it - I have the DNS part split out almost ready to go.

**Comment by mintopia** [comment]
You should be able to create them now.

I've also made a dockerhub organisation too.

**Pull request merged**
